# Generated by Django 2.1.3 on 2020-02-18 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainTask',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_column='task_id', max_length=255, verbose_name='任务ID')),
                ('start_time', models.DateTimeField(db_column='start_time', max_length=255, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(db_column='end_time', max_length=255, verbose_name='结束时间')),
                ('host_id', models.CharField(db_column='host_id', max_length=255, verbose_name='服务器')),
                ('gpu_id', models.CharField(db_column='gpu_id', max_length=255, verbose_name='GPU')),
                ('task_name', models.CharField(db_column='task_name', max_length=255, verbose_name='任务名')),
                ('infos', models.TextField(blank=True, db_column='infos', max_length=4000, verbose_name='备注')),
                ('status', models.CharField(db_column='status', max_length=255, verbose_name='状态')),
                ('task_type', models.ForeignKey(db_column='task_type', on_delete=django.db.models.deletion.CASCADE, related_name='task_type', to='data_app.DataProHandle', verbose_name='任务类型')),
                ('train_data_name', models.ForeignKey(db_column='train_data_name', on_delete=django.db.models.deletion.CASCADE, related_name='train_data_name', to='data_app.DataProHandle', verbose_name='数据目录')),
                ('version', models.ForeignKey(db_column='version', on_delete=django.db.models.deletion.CASCADE, related_name='version', to='data_app.DataProHandle', verbose_name='服务版本')),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
                'db_table': 'train_task',
            },
        ),
    ]
