# Generated by Django 2.1.3 on 2020-02-18 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProHandle',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_column='task_id', max_length=255, verbose_name='任务ID')),
                ('start_time', models.DateTimeField(db_column='start_time', max_length=255, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(db_column='end_time', max_length=255, verbose_name='结束时间')),
                ('dir_name', models.CharField(db_column='dir_name', max_length=255, verbose_name='目录名')),
                ('data_task_type', models.CharField(db_column='data_task_type', max_length=255, verbose_name='任务类型')),
                ('data_version', models.CharField(db_column='data_version', max_length=255, verbose_name='服务版本')),
                ('infos', models.TextField(db_column='infos', max_length=4000, verbose_name='备注')),
                ('status', models.CharField(db_column='status', max_length=255, verbose_name='状态')),
            ],
            options={
                'verbose_name': '数据预处理',
                'verbose_name_plural': '数据预处理',
                'db_table': 'data_preprocess',
            },
        ),
        migrations.CreateModel(
            name='ProData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_column='task_id', max_length=255, verbose_name='任务ID')),
                ('id_code', models.CharField(db_column='id_code', max_length=255, verbose_name='查询ID')),
                ('pro_data_type', models.CharField(db_column='pro_data_type', max_length=255, verbose_name='类型')),
                ('pro_dir_name', models.CharField(db_column='pro_dir_name', max_length=255, verbose_name='目录名')),
                ('infos', models.TextField(db_column='infos', max_length=4000, verbose_name='备注')),
                ('status', models.CharField(db_column='status', max_length=255, verbose_name='状态')),
            ],
            options={
                'verbose_name': '预处理数据',
                'verbose_name_plural': '预处理数据',
                'db_table': 'pro_data',
            },
        ),
        migrations.AddField(
            model_name='dataprohandle',
            name='src_dir_name',
            field=models.ForeignKey(db_column='src_dir_name', on_delete=django.db.models.deletion.CASCADE, related_name='src_dir_name', to='data_app.ProData', verbose_name='源数据目录'),
        ),
    ]
